In [7]:
import numpy as np

a = [[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]]

b = np.array(a)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [9]:
#01 [:,1:3]
#02 df[df['Curso'] == 'Matemática']['Nome', 'Nota']
#03 Verdadeiro
#04 np.arange(1, 10, 1).reshape(3,3)
#05 df['Câmpus'].groupby(df['Nota']).mean()
#06 df['Câmpus'].drop_duplicates().count()

#07
#np.arange(5) array([0, 1, 2, 3, 4])
#np.linspace(0, 20, 5) array([ 0.,  5., 10., 15., 20.])
#np.arange(10,15) [10, 11, 12, 13, 14]

#08 Seleciona a terceira coluna pela posição de um inteiro.

#09
#a = np.arange(5)

#a.max() 4

# a.sum() 10

#a.mean() 2.0

# Respostas duplicadas

#10 Verdadeiro

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14],
       [17, 18]])

In [ ]:
#02 df[df['Curso'] == 'Matemática']['Nome', 'Nota']

In [ ]:
#03 Verdadeiro

In [16]:
#04
np.arange(1, 10, 1).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
#05
df['Câmpus'].groupby(df['Nota']).mean()

In [ ]:
#06 df['Câmpus'].drop_duplicates().count()

In [22]:
#07
#np.arange(5) array([0, 1, 2, 3, 4])
#np.linspace(0, 20, 5) array([ 0.,  5., 10., 15., 20.])
#np.arange(10,15) [10, 11, 12, 13, 14]

array([0, 1, 2, 3, 4]), array([ 0.,  5., 10., 15., 20.]) e array([10, 11, 12, 13, 14])

array([0, 1, 2, 3, 4])

In [ ]:
#08
Seleciona a terceira coluna pela posição de um inteiro.

In [28]:
#09
#a = np.arange(5)

#a.max() 4

# a.sum() 10

#a.mean() 2.0

# Respostas duplicadas

2.0

In [ ]:
#10
Verdadeiro