In [1]:
import numpy as np
import statistics

# Leitura dados de classificação racial 2017 - Integrado e Proeja
data_2017 = np.genfromtxt('tmp_files/classificacao-racial-cti-eja-2017.csv', delimiter=',', dtype=None)
data_2017

array([   6, 1711,    9,  252,  140, 4563,    2,  355,    4,   64,   51,
        114])

In [2]:
# Leitura dados de classificação racial 2018 - Integrado e Proeja
data_2018 = np.genfromtxt('tmp_files/classificacao-racial-cti-eja-2018.csv', delimiter=',', dtype=None)
data_2018

array([   7, 2131,   12,  334,  208, 4331,    2,  353,    9,   81,   69,
        206])

In [3]:
# Leitura dados de classificação racial 2019 - Integrado e Proeja
data_2019 = np.genfromtxt('tmp_files/classificacao-racial-cti-eja-2019.csv', delimiter=',', dtype=None)
data_2019

array([  12, 2900,   10,  462,  275, 3691,    1,  363,    7,   88,   75,
        159])

In [4]:
# Leitura dados de classificação racial 2020 - Integrado e Proeja
data_2020 = np.genfromtxt('tmp_files/classificacao-racial-cti-eja-2020.csv', delimiter=',', dtype=None)
data_2020

array([  18, 3538,   13,  521,  277, 3331,    2,  399,    1,   83,   66,
        477])

In [5]:
# concatenando valores
lista_quantidades = np.concatenate((data_2017,data_2018,data_2019,data_2020))
sorted(lista_quantidades)

[1,
 1,
 2,
 2,
 2,
 4,
 6,
 7,
 7,
 9,
 9,
 10,
 12,
 12,
 13,
 18,
 51,
 64,
 66,
 69,
 75,
 81,
 83,
 88,
 114,
 140,
 159,
 206,
 208,
 252,
 275,
 277,
 334,
 353,
 355,
 363,
 399,
 462,
 477,
 521,
 1711,
 2131,
 2900,
 3331,
 3538,
 3691,
 4331,
 4563]

In [6]:
# média
statistics.mean(lista_quantidades)

662

In [7]:
# mediana
statistics.median(lista_quantidades)

101.0

In [8]:
# moda
statistics.mode(lista_quantidades)

2

In [9]:
# variância
statistics.variance(lista_quantidades)

1562075

In [10]:
# desvio padrão
print('{:.2f}'.format(statistics.stdev(lista_quantidades)))

1249.83


In [22]:
l=[140,51,208,69,275,75,277,66] 
#statistics.mean(l)
#statistics.median(l)
#statistics.mode(l)
print('{:.2f}'.format(statistics.stdev(l)))



95.67
